name: regex-applicative-text
version: 0.1.0.0
synopsis: regex-applicative on text
description: Wrapped regex-applicative primitives to work with Text
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/regex-applicative-text
category: Text
extra-source-files: README.md
tested-with: GHC==7.0.4, GHC==7.2.2, GHC==7.4.1, GHC==7.6.3, GHC==7.8.4, GHC==7.10.2

ghc-options: -Wall

dependencies:
  - base >= 4.3 && <4.9
  - regex-applicative >=0.3 && <0.4
  - text

library:
  source-dirs: src
